#!/usr/bin/node
var exec = require('child_process').exec;

mode=process.argv[2];
switch(mode) {
    case "config": 
        config(); 
        break;
    default: print();
}

function config() {
    console.log("graph_title VM dirty parameters");
    //console.log("graph_vlabel Values"); 
    console.log("vm.dirty_background_ratio.label Background Ratio");
    console.log("vm.dirty_background_bytes.label Background Bytes(MB)");
    console.log("vm.dirty_ratio.label Ratio(MB)");
    console.log("vm.dirty_bytes.label Bytes(MB)");
    console.log("vm.dirty_writeback_centisecs.label Writeback (csec)");
    console.log("vm.dirty_expire_centisecs.label Expire (csec)");
}

function print() {
    exec("sysctl -a", function(error, stdout, stderr) { 
        var lines = stdout.split("\n");
        var attrs = {};
        lines.forEach(function(line) {
            var tokens = line.split(" = ");
            //only interested in vm.dirty_
            if(tokens[0].indexOf("vm.dirty_") === 0) {
                //format some values
                var value = tokens[1];
                switch(tokens[0]) {
                case "vm.dirty_background_bytes":
                case "vm.dirty_bytes":
                    value /= 1024*1024;
                    break;
                }
                console.log(tokens[0]+".value "+value);
            }
        });
    });
}

